### ISSUE TITLE
search エラー

### ISSUE THREAD

**Issue by akihironitta** [daddygongon/my_help#91]
# 環境
os: Debian GNU/Linux 10
ruby: 2.5.5
gem: 2.7.6.2
shell: zsh 5.7.1 (x86_64-debian-linux-gnu)

# エラー文
```
nitta@white:~/% my_help search 10
Traceback (most recent call last):
	7: from /home/nitta/.gems/bin/my_help:23:in `<main>'
	6: from /home/nitta/.gems/bin/my_help:23:in `load'
	5: from /home/nitta/.gems/gems/my_help-0.8.0/exe/my_help:52:in `<top (required)>'
	4: from /home/nitta/.gems/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	3: from /home/nitta/.gems/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	2: from /home/nitta/.gems/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	1: from /home/nitta/.gems/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/home/nitta/.gems/gems/my_help-0.8.0/exe/my_help:48:in `search': undefined method `search_help' for #<MyHelp::Control:0x0000560516973968> (NoMethodError)
```

**Comment by akihironitta** [comment]
version 0.8.2 で動きました。

```
nitta@white:~/% my_help search a                                                                                [16:26 Wed 11]
my_help search a
"a"
emacs.org
```
